
project_id = "lrgvwkcdatfwxcjvbymt"

[functions.voice-call-handler]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false

[functions.text-to-speech-twilio]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = true

[functions.ai-response-generator]
verify_jwt = true

[functions.realtime-voice-chat]
verify_jwt = false
