
project_id = "lrgvwkcdatfwxcjvbymt"

[functions.voice-call-handler]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true

[functions.ai-response-generator]
verify_jwt = true
