// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrgvwkcdatfwxcjvbymt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyZ3Z3a2NkYXRmd3hjanZieW10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTU2NTksImV4cCI6MjA2NTQ3MTY1OX0.5xc3tutvh5fCONDiaOjUZDvIx6W3Eb7WvyjvB5_TR_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);